CREATE TABLE `annonce` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `nom_annonce` text,
  `ville` text,
  `adresse` text,
  `code_postal` text,
  `prix` text,
  `surface` bigint DEFAULT NULL,
  `divisibilite` text,
  `disponibilite` text,
  `type_transaction` text,
  `type_bien` text,
  `lien` text,
  `lien_photo` text,
  `contact` text,
  `site` text,
  `reference_du_site` text,
  `indication_prix` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14500 DEFAULT CHARSET=utf8;